# Generated by Django 4.2 on 2024-11-10 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("collector", "0001_initial_reddit_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="modified_dt",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="modified_dt",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="subreddit",
            name="modified_dt",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="DetectedInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collector.submission",
                    ),
                ),
            ],
        ),
    ]
