# Generated by Django 4.2 on 2024-11-11 12:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_distinguished_now_charfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='PydanticResponseFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='detectedinformation',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detectedinformation',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PydanticResponseFormatField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('str', 'String'), ('int', 'Integer'), ('float', 'Float'), ('bool', 'Boolean'), ('dict', 'Dictionary'), ('list', 'List'), ('tuple', 'Tuple'), ('set', 'Set'), ('none', 'None')], help_text='Select the Python data type', max_length=10)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
                ('base_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.pydanticresponseformat')),
            ],
        ),
        migrations.CreateModel(
            name='InformationToDetect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_instruction_message', models.TextField(help_text='Message that will be provided to the LLM model to instruct it what to do.')),
                ('response_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.pydanticresponseformat')),
            ],
        ),
        migrations.AddField(
            model_name='detectedinformation',
            name='information_tsf',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collector.informationtodetect'),
            preserve_default=False,
        ),
    ]
