# Generated by Django 4.2 on 2024-11-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_info_detection_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectSubmissionTaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('notstarted', 'Not Started'), ('started', 'Started'), ('finished', 'Finished')], default='not-started', max_length=15)),
                ('result', models.CharField(choices=[('notstarted', 'Not Started'), ('started', 'Started'), ('finished', 'Finished')], default='pending', max_length=15)),
                ('error_message', models.TextField()),
                ('error_traceback', models.TextField()),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
                ('initiated_dt', models.DateTimeField(blank=True, null=True)),
                ('stopped_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
