# Generated by Django 4.2 on 2024-11-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_collectsubmissiontaskrun_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectsubmissiontaskrun',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
